name: database_test
version: '1.0'
main: me.jonis.database_test.Database_test
api-version: '1.21'
authors: [ aunique ]
description: first plugin
commands:
  parkours:
    description: lists all parkours
  parkour:
    description: does stats!!
  viewstats:
    description: views a plays stats
    aliases: stats

